### ISSUE TITLE
Does not work with Cinnamon 2.4.5

### ISSUE THREAD

**Issue by UweHeim** [fastrde/morePanels#1]
The version 2.2 is hardcoded in the metadata.json
first it could not be added to cinnamon at all.

Then I tried to replace 
 "cinnamon-version": ["2.2"]
in metadata.json by
 "cinnamon-version": ["2.4"] or even "cinnamon-version": ["2.4.5"] 
it can added to cinnamon then,
but as an unfortunate did not work. Still reporting "incompatible version"

Would be great to have that for 2.4.x

**Comment by AgustinJB** [comment]
Ir works for me, but....just under some circumstances. 

I can enable it when cinnamon has alredy started, but if I let it enabled and then restart the pc, then cinnamon won't start. In that case I need to delete the folder of the extensions and start cinnamon again.

But if I enable it after cinnamon has started and disable just before I turn off the computer, it works fine.

**Comment by dawez** [comment]
Also noted that after changing the medata, it does not work with cinnamon 2.4.6

**Comment by fastrde** [comment]
No reason for further development on this plugin
see: https://github.com/linuxmint/Cinnamon/issues/130#issuecomment-74875552
